
  // ---- Simple account creation + login ----
  (function setupAuth(){
    const screen=document.getElementById('authScreen'), form=document.getElementById('loginForm'), email=document.getElementById('loginEmail'), password=document.getElementById('loginPassword'), submit=document.getElementById('loginSubmit'), error=document.getElementById('loginError'), status=document.getElementById('loginStatus'), toggle=document.getElementById('togglePassword'), logout=document.getElementById('logoutBtn'), modeToggle=document.getElementById('authModeToggle'), title=document.getElementById('loginTitle'), subtitle=document.getElementById('loginSubtitle'), switchText=document.getElementById('switchText'), note=document.getElementById('authNote');
    let createMode=false;
    function showError(m){error.textContent=m;error.classList.add('show');status.classList.remove('show')}
    function showStatus(m){status.textContent=m;status.classList.add('show');error.classList.remove('show')}
    function setAuthenticated(user){if(!user)return;screen.classList.add('hidden');document.body.classList.remove('auth-locked');logout.classList.add('visible');logout.title='Sign out '+(user.email||'');window.__appEntered=true;window.dispatchEvent(new Event('appenter'))}
    function setMode(create){createMode=create;title.textContent=create?'Create your account':'Welcome';subtitle.textContent=create?'Create an account once, then use it every time you return.':'Log in to continue to your case-taking workspace.';submit.textContent=create?'Create account':'Log in';switchText.textContent=create?'Already have an account?':'New here?';modeToggle.textContent=create?'Log in':'Create account';note.textContent=create?'Use an email and password you will remember. Your account is saved securely by the connected Supabase service.':'Create your account once. Next time, just enter the same email and password to log in.';error.classList.remove('show');status.classList.remove('show');password.value='';password.setAttribute('autocomplete',create?'new-password':'current-password')}
    toggle.addEventListener('click',()=>{const x=password.type==='password';password.type=x?'text':'password';toggle.textContent=x?'HIDE':'SHOW'}); modeToggle.addEventListener('click',()=>setMode(!createMode));
    form.addEventListener('submit',async e=>{e.preventDefault();error.classList.remove('show');submit.disabled=true;if(!dbEnabled||!supabaseClient){showError('The account system is not configured.');submit.disabled=false;return}const mail=email.value.trim();if(!mail||password.value.length<6){showError('Please enter a valid email and a password of at least 6 characters.');submit.disabled=false;return}showStatus(createMode?'Creating your account…':'Logging you in…');if(createMode){const {data,error:authError}=await supabaseClient.auth.signUp({email:mail,password:password.value});if(authError){showError(authError.message);submit.disabled=false;return}if(data.session&&data.user){showStatus('Account created! Opening your workspace…');setAuthenticated(data.user)}else{showStatus('Account created! Check your email to confirm your account, then log in.');setMode(false);email.value=mail}}else{const {data,error:authError}=await supabaseClient.auth.signInWithPassword({email:mail,password:password.value});if(authError){showError(authError.message);submit.disabled=false;return}setAuthenticated(data.user)}submit.disabled=false});
    logout.addEventListener('click',async()=>{if(supabaseClient)await supabaseClient.auth.signOut();logout.classList.remove('visible');screen.classList.remove('hidden');document.body.classList.add('auth-locked');password.value='';error.classList.remove('show');status.classList.remove('show');email.focus();window.__appEntered=false;window.dispatchEvent(new Event('appexit'))});
    async function restoreSession(){if(!dbEnabled||!supabaseClient){showError('The account system is not configured.');return}const {data}=await supabaseClient.auth.getSession();if(data?.session?.user)setAuthenticated(data.session.user);else email.focus()}
    if(supabaseClient)supabaseClient.auth.onAuthStateChange((event,session)=>{if(session?.user)setAuthenticated(session.user)}); restoreSession();
  })();
